server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
#server:
#  port: 8761
#
#eureka:
#  instance:
#    hostname: "${HOSTNAME}.eureka"
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER_ADDRESS}